# Generated by Django 6.0.5 on 2026-05-13 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('birthday', 'Anniversaire'), ('wedding', 'Mariage'), ('graduation', 'Diplômation')], default='birthday', max_length=20, verbose_name='Catégorie')),
                ('beneficiary_name', models.CharField(max_length=100, verbose_name='Nom du bénéficiaire')),
                ('beneficiary_phone', models.CharField(max_length=20, verbose_name='Téléphone du bénéficiaire')),
                ('background_media', models.FileField(upload_to='fundraisers/backgrounds/', verbose_name="Média d'arrière-plan")),
                ('media_type', models.CharField(choices=[('video', 'Vidéo'), ('image', 'Image')], default='image', max_length=10, verbose_name='Type de média')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='fundraisers/thumbnails/', verbose_name='Vignette (pour vidéo)')),
                ('button_text', models.CharField(default='Contribuer', max_length=100, verbose_name='Texte du bouton')),
                ('button_color', models.CharField(default='#FF6B6B', max_length=7, verbose_name='Couleur du bouton (Hex)')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Objectif (FCFA)')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Collecté (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Collecte',
                'verbose_name_plural': 'Collectes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundraiserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_update_amount', models.BooleanField(default=True, verbose_name='Mise à jour automatique')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='Devise')),
                ('send_notification_email', models.BooleanField(default=True, verbose_name='Envoyer notification email')),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de notification')),
                ('allow_donations', models.BooleanField(default=True, verbose_name='Autoriser les dons')),
                ('show_donor_list', models.BooleanField(default=False, verbose_name='Afficher la liste des donateurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fundraiser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.fundraiser')),
            ],
            options={
                'verbose_name': 'Paramètres de collecte',
                'verbose_name_plural': 'Paramètres de collectes',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('donor_phone', models.CharField(max_length=20, verbose_name='Téléphone du donateur')),
                ('provider', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Africa')], max_length=10, verbose_name='Opérateur')),
                ('openpay_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction OpenPay')),
                ('openpay_link', models.URLField(blank=True, null=True, verbose_name='Lien de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complétée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du donateur')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message de vœux')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.fundraiser', verbose_name='Collecte')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fundraiser', 'status'], name='core_transa_fundrai_281059_idx'), models.Index(fields=['openpay_transaction_id'], name='core_transa_openpay_ffb360_idx')],
            },
        ),
    ]
