# Generated by Django 6.0.5 on 2026-05-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='min_donation_amount',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=12, verbose_name='Montant minimum (FCFA)'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Objectif (FCFA - Optionnel)'),
        ),
    ]
