# Generated by Django 6.0.5 on 2026-05-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fundraiser_min_donation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money')], max_length=10, verbose_name='Opérateur'),
        ),
    ]
