# Generated by Django 6.0.5 on 2026-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du donateur'),
        ),
    ]
