# Generated by Django 6.0.5 on 2026-05-13 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_donor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='min_donation_amount',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=12, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Montant minimum (FCFA)'),
        ),
    ]
