# Generated by Django 6.0.5 on 2026-05-31 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fundraiser_min_donation_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='beneficiary_image',
            field=models.ImageField(blank=True, null=True, upload_to='fundraisers/beneficiaries/', verbose_name='Photo du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraisers', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
    ]
