# Generated by Django 6.0.5 on 2026-06-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
    ]
