# Generated by Django 6.0.5 on 2026-05-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du candidat')),
                ('image', models.ImageField(upload_to='votes/choices/', verbose_name='Photo du candidat')),
                ('description', models.TextField(blank=True, verbose_name='Description/Bio')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de votes')),
            ],
        ),
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du vote')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('background_image', models.ImageField(upload_to='votes/backgrounds/', verbose_name="Image d'arrière-plan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Session de Vote',
                'verbose_name_plural': 'Sessions de Vote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du votant')),
                ('voter_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du votant')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé (si applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.candidate', verbose_name='Candidat')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='votes.votesession', verbose_name='Session de vote'),
        ),
    ]
