# Generated by Django 6.0.5 on 2026-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesession',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='organizer_image',
            field=models.ImageField(blank=True, null=True, upload_to='votes/organizers/', verbose_name="Image de l'organisateur"),
        ),
        migrations.AddField(
            model_name='votesession',
            name='organizer_name',
            field=models.CharField(default='Tosounga', max_length=100, verbose_name='Organisateur'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='vote_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'un vote (FCFA)"),
        ),
    ]
