# Generated by Django 6.0.5 on 2026-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_votesession_is_verified_votesession_organizer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='category',
            field=models.CharField(choices=[('music', 'Musique'), ('sport', 'Sport'), ('beauty', 'Beauté & Miss'), ('education', 'Éducation'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['candidate', 'ip_address'], name='votes_voter_candida_c631da_idx'),
        ),
    ]
