# Generated by Django 6.0.5 on 2026-05-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_voterecord_ip_address_votesession_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'option")),
                ('image', models.ImageField(upload_to='votes/choices/', verbose_name="Image d'illustration")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de votes')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='session',
        ),
        migrations.RemoveIndex(
            model_name='voterecord',
            name='votes_voter_candida_c631da_idx',
        ),
        migrations.AddField(
            model_name='choice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='votes.votesession', verbose_name='Session de vote'),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.choice', verbose_name='Choix'),
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['choice', 'ip_address'], name='votes_voter_choice__b80d1d_idx'),
        ),
        migrations.RemoveField(
            model_name='voterecord',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
