# Generated by Django 6.0.5 on 2026-05-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_choice_remove_candidate_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterecord',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.choice', verbose_name='Choix'),
        ),
    ]
