# Generated by Django 6.0.5 on 2026-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_alter_voterecord_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterecord',
            name='openpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction OpenPay'),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], default='completed', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['openpay_transaction_id'], name='votes_voter_openpay_a6285b_idx'),
        ),
    ]
