# Generated by Django 6.0.5 on 2026-05-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_voterecord_openpay_transaction_id_voterecord_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesession',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin du vote'),
        ),
    ]
