# Generated by Django 6.0.5 on 2026-06-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la règle')),
                ('content', models.TextField(verbose_name='Contenu de la règle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Règle de la plateforme',
                'verbose_name_plural': 'Règles de la plateforme',
                'ordering': ['order', 'title'],
            },
        ),
    ]
